name: "기능 추가"
description: 기능 추가 Issue 작성 양식입니다.
title: "[feat] "
body:
  - type: markdown
    attributes:
      value: |
        작성 예시 : "[feat] client class 구현"
  - type: textarea
    id: bug-description
    attributes:
      label: 작업 설명
      description: 어떠한 기능을 추가하시는 건지 적어주세요.
      placeholder: 설명을 적어주세요.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: 접근 방법 및 참고 자료
      description: 고려하신 방법이나 자료에 대해서 설명해주세요.
      placeholder: 설명을 적어주세요.
    validations:
      required: true
